FROM buildpack-deps:bullseye

LABEL description="cppcheck 使用 distcc 所需的环境"
LABEL project="https://github.com/uhziel/demo-k8s-distcc"

ENV LANG="C.UTF-8"
ENV TZ="Asia/Shanghai"

RUN set -eux; \
        sed -i~ 's/http:\/\/\w*\.debian\.org/http:\/\/mirrors.tuna.tsinghua.edu.cn/' /etc/apt/sources.list; \
        apt-get update; \
        apt-get install -y --no-install-recommends \
            cmake \
            distcc \
        ; \
        rm -rf /var/lib/apt/lists/*;
